"""add tool calls

Revision ID: 4a84bc00b643
Revises: fccbd979f32f
Create Date: 2026-07-13 17:00:07.798814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4a84bc00b643'
down_revision: Union[str, Sequence[str], None] = 'fccbd979f32f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tool_calls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('node_run_id', sa.Integer(), nullable=False),
    sa.Column('tool_name', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('external_tool_call_id', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'running', 'completed', 'failed', name='tool_call_status'), server_default='pending', nullable=False),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('arguments', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['node_run_id'], ['node_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tool_calls_external_tool_call_id'), 'tool_calls', ['external_tool_call_id'], unique=False)
    op.create_index(op.f('ix_tool_calls_node_run_id'), 'tool_calls', ['node_run_id'], unique=False)
    op.create_index(op.f('ix_tool_calls_provider'), 'tool_calls', ['provider'], unique=False)
    op.create_index(op.f('ix_tool_calls_status'), 'tool_calls', ['status'], unique=False)
    op.create_index(op.f('ix_tool_calls_tool_name'), 'tool_calls', ['tool_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tool_calls_tool_name'), table_name='tool_calls')
    op.drop_index(op.f('ix_tool_calls_status'), table_name='tool_calls')
    op.drop_index(op.f('ix_tool_calls_provider'), table_name='tool_calls')
    op.drop_index(op.f('ix_tool_calls_node_run_id'), table_name='tool_calls')
    op.drop_index(op.f('ix_tool_calls_external_tool_call_id'), table_name='tool_calls')
    op.drop_table('tool_calls')
    # ### end Alembic commands ###
