"""add tasks and task runs

Revision ID: ece0918d6fee
Revises: 4a84bc00b643
Create Date: 2026-07-14 11:33:38.503232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ece0918d6fee'
down_revision: Union[str, Sequence[str], None] = '4a84bc00b643'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_run_id', sa.Integer(), nullable=False),
    sa.Column('parent_task_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('objective', sa.String(), nullable=False),
    sa.Column('agent_type', sa.Enum('general', 'research', 'coding', 'memory', 'rag', 'synthesis', 'judge', 'router', name='agent_type'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'ready', 'running', 'completed', 'failed', 'skipped', 'cancelled', name='task_status'), server_default='pending', nullable=False),
    sa.Column('position', sa.Integer(), nullable=False, server_default='0'),
    sa.Column('priority', sa.Enum('low', 'medium', 'high', 'critical', name='task_priority'), server_default='medium', nullable=False),
    sa.Column('depends_on', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default=sa.text("'[]'::jsonb")),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('is_terminal', sa.Boolean(), nullable=False, server_default='false'),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_task_id'], ['tasks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_agent_run_id'), 'tasks', ['agent_run_id'], unique=False)
    op.create_index(op.f('ix_tasks_agent_type'), 'tasks', ['agent_type'], unique=False)
    op.create_index(op.f('ix_tasks_parent_task_id'), 'tasks', ['parent_task_id'], unique=False)
    op.create_index(op.f('ix_tasks_priority'), 'tasks', ['priority'], unique=False)
    op.create_index(op.f('ix_tasks_status'), 'tasks', ['status'], unique=False)
    op.create_table('task_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'completed', 'failed', 'skipped', 'interrupted', 'cancelled', name='execution_status'), server_default='pending', nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('output_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('attempt_number', sa.Integer(), nullable=False, server_default='1'),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_runs_status'), 'task_runs', ['status'], unique=False)
    op.create_index(op.f('ix_task_runs_task_id'), 'task_runs', ['task_id'], unique=False)
    op.add_column('node_runs', sa.Column('task_run_id', sa.Integer(), nullable=False))
    op.drop_index(op.f('ix_node_runs_agent_run_id'), table_name='node_runs')
    op.create_index(op.f('ix_node_runs_task_run_id'), 'node_runs', ['task_run_id'], unique=False)
    op.drop_constraint(op.f('node_runs_agent_run_id_fkey'), 'node_runs', type_='foreignkey')
    op.create_foreign_key("fk_node_runs_task_run_id", 'node_runs', 'task_runs', ['task_run_id'], ['id'], ondelete='CASCADE')
    op.drop_column('node_runs', 'agent_run_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('node_runs', sa.Column('agent_run_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint("fk_node_runs_task_run_id", 'node_runs', type_='foreignkey')
    op.create_foreign_key(op.f('node_runs_agent_run_id_fkey'), 'node_runs', 'agent_runs', ['agent_run_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_node_runs_task_run_id'), table_name='node_runs')
    op.create_index(op.f('ix_node_runs_agent_run_id'), 'node_runs', ['agent_run_id'], unique=False)
    op.drop_column('node_runs', 'task_run_id')
    op.drop_index(op.f('ix_task_runs_task_id'), table_name='task_runs')
    op.drop_index(op.f('ix_task_runs_status'), table_name='task_runs')
    op.drop_table('task_runs')
    op.drop_index(op.f('ix_tasks_status'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_priority'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_parent_task_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_agent_type'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_agent_run_id'), table_name='tasks')
    op.drop_table('tasks')
    # ### end Alembic commands ###
