"""add node runs

Revision ID: fccbd979f32f
Revises: b2235ca49aaa
Create Date: 2026-07-13 16:28:55.702898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fccbd979f32f'
down_revision: Union[str, Sequence[str], None] = 'b2235ca49aaa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('node_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_run_id', sa.Integer(), nullable=False),
    sa.Column('parent_node_run_id', sa.Integer(), nullable=True),
    sa.Column('node_name', sa.String(), nullable=False),
    sa.Column('node_type', sa.Enum('planner', 'agent', 'tool', 'mcp', 'router', 'memory', 'rag', 'synthesis', name='node_type'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'completed', 'failed', 'skipped', name='node_run_status'), server_default='pending', nullable=False),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('input_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('output_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_node_run_id'], ['node_runs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_node_runs_agent_run_id'), 'node_runs', ['agent_run_id'], unique=False)
    op.create_index(op.f('ix_node_runs_node_name'), 'node_runs', ['node_name'], unique=False)
    op.create_index(op.f('ix_node_runs_node_type'), 'node_runs', ['node_type'], unique=False)
    op.create_index(op.f('ix_node_runs_parent_node_run_id'), 'node_runs', ['parent_node_run_id'], unique=False)
    op.create_index(op.f('ix_node_runs_status'), 'node_runs', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_node_runs_status'), table_name='node_runs')
    op.drop_index(op.f('ix_node_runs_parent_node_run_id'), table_name='node_runs')
    op.drop_index(op.f('ix_node_runs_node_type'), table_name='node_runs')
    op.drop_index(op.f('ix_node_runs_node_name'), table_name='node_runs')
    op.drop_index(op.f('ix_node_runs_agent_run_id'), table_name='node_runs')
    op.drop_table('node_runs')
    # ### end Alembic commands ###
