"""add active message

Revision ID: fcce4c70cbcf
Revises: 58d6bd652565
Create Date: 2026-07-12 03:48:51.352663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcce4c70cbcf'
down_revision: Union[str, Sequence[str], None] = '58d6bd652565'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('threads', sa.Column('active_message_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_threads_active_message_id'), 'threads', ['active_message_id'], unique=False)
    op.create_foreign_key('fk_threads_active_message_id_messages', 'threads', 'messages', ['active_message_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_threads_active_message_id_messages', 'threads', type_='foreignkey')
    op.drop_index(op.f('ix_threads_active_message_id'), table_name='threads')
    op.drop_column('threads', 'active_message_id')
    # ### end Alembic commands ###
